//
//  Movie.swift
//  BeautifulAnimanion
//
//  Created by evilb on 02.04.2022.
//

import SwiftUI

// MARK: Movie Data Model and Sample Movie Data
struct Movie: Identifiable {
    var id = UUID().uuidString
    var movieTitle: String
    var artwork: String
    var storyPlot: String
}

var movies: [Movie] = [
    Movie(movieTitle: "Mad Max", artwork: "Movie1", storyPlot: "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and almost everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order. There's Max, a man of action and a man of few words, who seeks peace of mind following the loss of his wife and child in the aftermath of the chaos. And Furiosa, a woman of action and a woman who believes her path to survival may be achieved if she can make it across the desert back to her childhood homeland."),
    Movie(movieTitle: "Alita Battle Angel", artwork: "Movie2", storyPlot: "In 2563, three hundred years after the war 'The Fall', the mysterious scientist Dr. Dyson Ido finds part of a female cyborg in a junkyard and brings to his laboratory. He finds that her human brain is amnetic but intact and gives the name of his deceased daughter Alita to the cyborg. Alita meets on the street Dr. Ido's ex-wife Chiren, who is also a scientist that works to the powerful Zapan, and befriends the young Hugo, who brings cyborg's parts to Dr. Ido, and learns that both dream on moving to the floating city of Zalem. Hugo teaches Alita how to play Motorball and she learns that the champion of the Motorball Tournament moves to Zalem. Soon Alita discovers that Dr. Ido is a hunter warrior and after finding her cyborg body in a crashed spaceship, she decides to become also a hunter warrior but Dr. Ido refuses to replace her body. Who was Alita and what is the secret of the cyborg body found by Alita?Let us see what happens."),
    Movie(movieTitle: "Star Wars", artwork: "Movie3", storyPlot: "While the First Order continues to ravage the galaxy, Rey finalizes her training as a Jedi. But danger suddenly rises from the ashes as the evil Emperor Palpatine mysteriously returns from the dead. While working with Finn and Poe Dameron to fulfill a new mission, Rey will not only face Kylo Ren once more, but she will also finally discover the truth about her parents as well as a deadly secret that could determine her future and the fate of the ultimate final showdown that is to come."),
    Movie(movieTitle: "Blade Runner 2049", artwork: "Movie4", storyPlot: "2049. It's been approximately two decades since the Tyrell Corporation, the creators and original manufacturers of replicants (bioengineered superhumans), went bankrupt, a new generation of replicants manufactured by industrialist Niander Wallace who saved the world with his replicants in establishing synthetic farming in light of collapsing natural ecosystems. While the replicants of the Tyrell era are now outlawed in they having violently rebelled, they 'retired' (aka destroyed) by blade runners, the Wallace era replicants, which have been programmed to obey, are seen as necessary to society. Many current day blade runners are Wallace era replicants. K, short for his serial number KD6-3.7, is one such blade runner working for the LAPD under Lieutenant Joshi. On one of his assignments, K discovers what he believes are human remains, but on forensic examination are actually the remains of a female replicant who has signs of having given birth during her life, presumably to a human baby. Joshi, fearing the worst of what this finding actually means and it getting into the wrong hands, orders K to discover and destroy any evidence of this finding, which includes locating the baby, probably now grown, and destroying him/her. As K discovers some further evidence to this story concerning his own history (each replicant which is implanted with a manufactured and thus not real history), K begins to suspect that this story may be a little more than just a professional assignment to him and which may jeopardize his future beyond that information getting into the wrong hands with which he will also have to deal."),
    Movie(movieTitle: "Joker", artwork: "Movie5", storyPlot: "Struggling to make people laugh in grim early-1980s Gotham City, the mentally ill street clown and failed stand-up comedian, Arthur Fleck, wears his smudgy makeup every day to eke out an existence. Mocked, bullied, and above all, marginalised, Fleck's slippery grip on reality will pave the way for a gradual descent into a dark world of unrestrained violence, as a loaded revolver enters the picture offering the long-awaited liberation. Then, the medications stopped working, and troubled Arthur's fierce hatred seems to be the only way out. Is the world prepared for the gloriously malevolent advent of the grinned super-villain, Joker?"),
    Movie(movieTitle: "Warcraft", artwork: "Movie6", storyPlot: "When the world of the Orcs of Draenor is being destroyed by the evil fel magic that uses life-force, the powerful warlock Gul'dan creates a portal to the world of Azeroth and forms the Horde with members of the Orc clans. He also captures many prisoners to keep the portal open. The king of Azeroth, Llane Wrynn and his brother-in-law, Anduin Lothar are informed by the apprentice of magician Khadgar that he has found fel magic in dead bodies and the king decides to summon the Guardian of Tirisfal, Medivh, to protect his kingdom. Lothar and Khadgar head to Kharazhan to meet Medivh and an ominous shadow points a book out to Khadgar, who takes it and hides. Anduin, Khadgar and Medivh and a group of soldiers are attacked by Orcs and they capture the slave Garona, who is released by King Llane, and she shows them the location of the portal. Garona is contacted by the Orc chief of a clan Durotan that wants to meet King Llane to stop the fel magic. Meanwhile Khadgar learns that the gate was opened with the help of someone in Azeroth. Shall King Llane trust Garona and Durotan, who might be the traitor?"),
    Movie(movieTitle: "Scott Piligrim vs the World", artwork: "Movie7", storyPlot: "Scott Pilgrim plays in a band which aspires to success. He dates Knives Chau, a high-school girl five years younger, and he hasn't recovered from being dumped by his former girlfriend, now a success with her own band. When Scott falls for Ramona Flowers, he has trouble breaking up with Knives and tries to romance Ramona. As if juggling two women wasn't enough, Ramona comes with baggage: seven ex-lovers, with each of whom Scott must do battle to the death in order to win Ramona.")
]

// MARK: Dummy Text

var sampleText = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,"
